-- 코드를 입력하세요
SELECT DISTINCT a.USER_ID, b.PRODUCT_ID
FROM ONLINE_SALE a, ONLINE_SALE b
WHERE a.USER_ID = b.USER_ID and a.PRODUCT_ID = b.PRODUCT_ID and a.ONLINE_SALE_ID != b.ONLINE_SALE_ID
ORDER BY  USER_ID, PRODUCT_ID DESC;