SELECT A.PRODUCT_CODE, (A.PRICE * B.SALES) AS SALES
FROM PRODUCT AS A JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) AS B 
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC;


